### ISSUE TITLE
NoSuchElementException in getLayer

### ISSUE THREAD

**Issue by stefanocke** [stefanocke/japkit#9]
In some complex scenario where generated code contained new trigger annotations, the following exception occured.

Caused by: java.util.NoSuchElementException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:713)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734)
	at java.util.Collections.max(Collections.java:669)
	at de.japkit.processor.JapkitProcessor.getLayer(JapkitProcessor.java:485)
	at de.japkit.processor.JapkitProcessor$21.apply(JapkitProcessor.java:456)
	at de.japkit.processor.JapkitProcessor$21.apply(JapkitProcessor.java:453)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:817)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators.addAll(Iterators.java:365)
	at com.google.common.collect.Iterables.addAll(Iterables.java:352)
	at com.google.common.collect.Sets.newLinkedHashSet(Sets.java:327)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.toSet(IterableExtensions.java:574)
	at de.japkit.processor.JapkitProcessor.getMinLayer(JapkitProcessor.java:460)
	at de.japkit.processor.JapkitProcessor.process(JapkitProcessor.java:383)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	... 24 more

**Comment by stefanocke** [comment]
Closed for now. If logging reveals real cause, it might be reconsidered again.
